# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-20 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0001_initial'),
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='liked_user',
            field=models.ManyToManyField(related_name='liked_quote', to='login_reg.User'),
        ),
    ]
